export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_SASS_FRAMEWORK_DATA_SUCCESS = 'LOAD_SASS_FRAMEWORK_DATA_SUCCESS';
export const UPDATE_SASS_FRAMEWORK_DATA_SUCCESS = 'UPDATE_SASS_FRAMEWORK_DATA_SUCCESS';
export const CREATE_SASS_FRAMEWORK_DATA_SUCCESS = 'CREATE_SASS_FRAMEWORK_DATA_SUCCESS';
